HTTP/2.0 200 OK
authenticated: false
cache-control: post-check=0, pre-check=0
content-length: 89
content-type: application/json; charset=utf-8
date: Tue, 29 Oct 2024 12:36:51 GMT
expires: Tue, 03 Jul 2001 06:00:00 GMT
last-modified: Tue Oct 29 2024 12:36:51 GMT+0000 (Coordinated Universal Time)
server: Google Frontend
strict-transport-security: max-age=15552000; includeSubDomains
vary: Origin
x-cloud-trace-context: 7c8b9786a69ca791c364be3955e76227
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-response-time: 1ms
x-xss-protection: 1; mode=block

[
  {
    "id": "bvj",
    "url": "https://cdn2.thecatapi.com/images/bvj.jpg",
    "width": 900,
    "height": 598
  }
]